### ISSUE TITLE
Promise not present under ES5

### ISSUE THREAD

**Issue by RobertoMalatesta** [afrische/ui5.d.ts#1]
A Promise declaration/implementation in file UI5.d.ts should be added while targeting ES5, like:
///<reference path="es6-promise.d.ts"/>
available from:
https://raw.githubusercontent.com/borisyankov/DefinitelyTyped/master/es6-promise/es6-promise.d.ts
and its relative package should be added to the project:
 npm install es6-promise --save

--R

**Comment by afrische** [comment]
Hallo Roberto,

i don't think adding dependencies is right for this project. I think the best way to use it, is to add a git submodule to a project's `typings/` folder ([tsd](http://definitelytyped.org/tsd/) adds one).

Most [thirdparty](https://github.com/SAP/openui5/tree/master/src/sap.ui.core/src/sap/ui/thirdparty) packages should have definition files in DefinitelyTyped and imo don't need to be replicated here.

Further, Promises are an ES6 feature and are part of typescript itself (lib.core.es6.d.ts) .

hth
Andreas

**Comment by RobertoMalatesta** [comment]
Perfect with that solution.
R
